config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :rawg_api do
    get '/creator-roles' => 'creator_roles#index'
    get '/creators' => 'creators#index'
    get '/developers' => 'developers#index'
    get '/games' => 'games#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/rawg_api/creator_roles_controller.rb
module RawgApi
  class CreatorRolesController < ApplicationController
    def index
      creator_roles = Rawg::Client.creator_roles
      creator_roles.each do |creator_role|
      end
      render json: creator_roles
    end   
  end
end

app/controllers/rawg_api/creators_controller.rb
module RawgApi
  class CreatorsController < ApplicationController
    def index
      creators = Rawg::Client.creators
      creators.each do |creator|
      end
      render json: creators
    end
  end
end

app/controllers/rawg_api/developers_controller.rb
module RawgApi
  class DevelopersController < ApplicationController
    def index
      developers = Rawg::Client.developers
      developers.each do |developer|
      end
      render json: developers
    end   
  end
end

app/controllers/rawg_api/games_controller.rb
module RawgApi
  class GamesController < ApplicationController
    def index
      games = Rawg::Client.games
      games.each do |game|
      end
      render json: games
    end   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creator_roles_helper.rb
module CreatorRolesHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">RAWG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">API</a>
        <%# <a class="nav-link" href="#">Pricing</a>
        <a class="nav-link disabled">Disabled</a> %>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="list-group">
  <%= link_to "Creator Roles", rawg_api_creator_roles_path, class: "btn btn-lg btn-light" %>
  <br/>
  
  <%= link_to "Creators", rawg_api_creators_path, class: "btn btn-lg btn-light" %>
  <br/>

  <%= link_to "Developers", rawg_api_developers_path, class: "btn btn-lg btn-light" %>
  <br/>

  <%= link_to "Games", rawg_api_games_path, class: "btn btn-lg btn-light" %>
  <br/>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>API Wrapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>